name: dockercicd

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Echo secrets
        run: |
          echo 'ERISKEY=${{ secrets.ERISKEY }}' >> .env
          echo 'AZUREPAT=${{ secrets.AZUREPAT }}' >> .env
          echo 'ORGNAME=knoxsdata' >> .env
          echo 'PROJECTNAME=knoxgates' >> .env
      - name: Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build image and push to repo
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: juicystake/chatbot:latest
          secrets: |
            "ERISKEY=${{ secrets.ERISKEY }}"
            "AZUREPAT=${{ secrets.AZUREPAT }}"
            "ORGNAME=knoxsdata"